-- Update properties table to match the current form structure
ALTER TABLE public.properties 
DROP COLUMN IF EXISTS property_type,
DROP COLUMN IF EXISTS building_size,
DROP COLUMN IF EXISTS units,
DROP COLUMN IF EXISTS occupancy,
DROP COLUMN IF EXISTS parking,
DROP COLUMN IF EXISTS big_ticket_items,
DROP COLUMN IF EXISTS gross_scheduled_income,
DROP COLUMN IF EXISTS operating_expenses,
DROP COLUMN IF EXISTS net_operating_income,
DROP COLUMN IF EXISTS cap_rate,
DROP COLUMN IF EXISTS cash_on_cash_return,
DROP COLUMN IF EXISTS comps,
DROP COLUMN IF EXISTS contact_name,
DROP COLUMN IF EXISTS contact_phone,
DROP COLUMN IF EXISTS contact_email,
DROP COLUMN IF EXISTS brokerage,
DROP COLUMN IF EXISTS additional_disclosures,
DROP COLUMN IF EXISTS primary_photo,
DROP COLUMN IF EXISTS additional_photos;

-- Add the actual columns used by the form
ALTER TABLE public.properties 
ADD COLUMN IF NOT EXISTS closing_date TEXT,
ADD COLUMN IF NOT EXISTS photo_link TEXT,
ADD COLUMN IF NOT EXISTS front_photo TEXT,
ADD COLUMN IF NOT EXISTS bedrooms TEXT,
ADD COLUMN IF NOT EXISTS bathrooms TEXT,
ADD COLUMN IF NOT EXISTS square_footage TEXT,
ADD COLUMN IF NOT EXISTS foundation_type TEXT,
ADD COLUMN IF NOT EXISTS utilities TEXT,
ADD COLUMN IF NOT EXISTS garage TEXT,
ADD COLUMN IF NOT EXISTS pool TEXT,
ADD COLUMN IF NOT EXISTS current_occupancy TEXT,
ADD COLUMN IF NOT EXISTS closing_occupancy TEXT,
ADD COLUMN IF NOT EXISTS include_financial_breakdown BOOLEAN,
ADD COLUMN IF NOT EXISTS arv TEXT,
ADD COLUMN IF NOT EXISTS rehab_estimate TEXT,
ADD COLUMN IF NOT EXISTS all_in TEXT,
ADD COLUMN IF NOT EXISTS gross_profit TEXT,
ADD COLUMN IF NOT EXISTS exit_strategy TEXT,
ADD COLUMN IF NOT EXISTS comps JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS contact_name TEXT,
ADD COLUMN IF NOT EXISTS contact_phone TEXT,
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS office_number TEXT,
ADD COLUMN IF NOT EXISTS business_hours TEXT,
ADD COLUMN IF NOT EXISTS contact_image TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS emd_amount TEXT,
ADD COLUMN IF NOT EXISTS emd_due_date TEXT,
ADD COLUMN IF NOT EXISTS post_possession TEXT,
ADD COLUMN IF NOT EXISTS additional_disclosures TEXT;