// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqlmeprrvijmcxvbaubq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbG1lcHJydmlqbWN4dmJhdWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTU1MTksImV4cCI6MjA3MjkzMTUxOX0.w47Sjdnpucv4Y5t8tx_xVuikn3E-sHDt0YRH1JXCSkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});